# docker-compose.yml
version: '3.8'
services:
  traefik:
    image: traefik
    container_name: traefik
    build:
      context: ./requirements/traefik
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
    #  - "traefik.http.routers.api.rule=Host(`traefik.your-domain.com`)"
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=motero@student.42.fr
      - --certificatesresolvers.myresolver.acme.storage=/acme.json
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence
    driver: bridge
