# docker-compose.override.yml
version: '3.8'
services:
  front-end:
    container_name: front-end
    build:
      context: ./requirements/front-end/
      dockerfile: Dockerfile.dev
    volumes:
      - ./requirements/front-end/react-app/:/app/src # Mount the source code
      # - /app/node_modules  # Mount node_modules separately to avoid overwriting
    ports:
      - "8033:8033"
    # environment:
      # - NODE_ENV=development