openapi: 3.0.0
info:
  title: Online Pong Game API
  version: "1.0"
  description: This API documentation covers all aspects of the Online Pong Game, including game management, user authentication, WebSocket communication for real-time game updates, and tournament organization.

servers:
  - url: https://localhost:9443
    description: Development server

paths:
  /game-logic/createMatch:
    post:
      summary: Create a new game match
      tags:
        - Game API
      requestBody:
        description: Match settings including number of players, game rounds, and game object properties.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMatchRequest'
      responses:
        200:
          description: Match created successfully with matchID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  matchID:
                    type: string

  /api/user_management/auth/login:
    post:
      summary: Login user
      tags:
        - User Management API
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Login successful, JWT provided in cookies.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /api/tournament/create-and-list/:
    post:
      summary: Create Tournament
      tags:
        - Tournament API
      requestBody:
        description: Tournament creation details.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTournamentRequest'
      responses:
        200:
          description: Tournament created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

components:
  schemas:
    CreateMatchRequest:
      type: object
      properties:
        gamemodeData:
          type: object
          properties:
            nbrOfPlayers:
              type: integer
            nbrOfRounds:
              type: integer
            timeLimit:
              type: integer
        fieldData:
          type: object
          properties:
            wallsFactor:
              type: integer
            sizeOfGoals:
              type: integer
        paddlesData:
          type: object
          properties:
            width:
              type: integer
            height:
              type: integer
            speed:
              type: number
        ballData:
          type: object
          properties:
            speed:
              type: number
            radius:
              type: integer
            color:
              type: string
        playersData:
          type: array
          items:
            type: object
            properties:
              accountID:
                type: string
              color:
                type: string

    LoginRequest:
      type: object
      properties:
        csrfmiddlewaretoken:
          type: string
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        message:
          type: string
        user:
          type: object
          properties:
            id:
              type: integer
            password:
              type: string
            last_login:
              type: string
            is_superuser:
              type: boolean
            username:
              type: string
            first_name:
              type: string
            last_name:
              type: string
            email:
              type: string
            is_staff:
              type: boolean
            is_active:
              type: boolean
            date_joined:
              type: string
            token:
              type: string
            playername:
              type: string
            is_online:
              type: boolean
            avatar:
              type: string
            game_stats:
              type: integer
            groups:
              type: array
            user_permissions:
              type: array
            friends:
              type: array
        redirect_url:
          type: string
        requires_2fa:
          type: boolean

    CreateTournamentRequest:
      type: object
      properties:
        tournament_name:
          type: string
        nbr_of_player:
          type: integer
        game_type:
          type: integer
        tournament_type:
          type: integer
        registration:
          type: integer
        registration_period_min:
          type: integer
        host_id:
          type: integer
        setting:
          type: object
          properties:
            duration_sec:
              type: integer
            max_score:
              type: integer
            walls_factor:
              type: integer
            size_of_goals:
              type: integer
            paddle_height:
              type: integer
            paddle_speed:
              type: number
            ball_speed:
              type: number
            ball_radius:
              type: integer
