# docker-compose.yml
version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: