# traefik/traefik.yml

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
      tls:
        certResolver: myresolver

certificatesResolvers:
  staging:
    acme:
      email: motero@student.42.fr
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: websecure
  production:
    acme:
      email: motero@student.42.fr
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: websecure

providers:
  docker:
    # -- (Optional) Enable this, if you want to expose all containers automatically
    exposedByDefault: false
    network: transcendence
  file:
    directory: /etc/traefik
    watch: true
