# docker-compose.yml
version: '3.9'
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 55432:5432
    networks:
      - backend
      
volumes:
  postgres-data:

networks:
  backend:
    driver: bridge